# Generated by Django 6.0.7 on 2026-07-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reason",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
