# Generated by Django 6.0.7 on 2026-07-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_appointment_reason"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="patientprofile",
            options={"ordering": ["user__last_name"]},
        ),
    ]
