# Generated by Django 6.0.7 on 2026-07-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_alter_department_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-date_time"]},
        ),
    ]
